# Welcome to Jekyll!
title: DM cave
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Serving
port: 8080

# collections
collections:
  wiki:
    output: true
    permalink: /:collection/:path/